project_id = "orxjqiegmocarwdedkpu"

[functions.auth0-provision]
verify_jwt = false

[functions.gamification-ping]
verify_jwt = true

[functions.leaderboard-daily]
verify_jwt = true

[functions.welcome-email]
verify_jwt = false