version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    reviewers: ["jbandu"]
