name: CI

on:
  push:
  pull_request:

jobs:
  install-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Authenticate to npm registry
        if: secrets.NPM_TOKEN != ''
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm ci
      - name: Upload node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

  lint:
    runs-on: ubuntu-latest
    needs: install-and-cache
    steps:
      - uses: actions/checkout@v4
      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Run linter
        run: npx eslint .

  test:
    runs-on: ubuntu-latest
    needs: install-and-cache
    steps:
      - uses: actions/checkout@v4
      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Run unit tests
        run: npx vitest
      - name: Run Playwright tests (optional)
        if: env.PLAYWRIGHT === 'true'
        run: npx playwright test
