name: Repair Lockfile

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  repair:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Ensure test deps in package.json
        run: |
          npm pkg set devDependencies["@playwright/test"]="1.55.0"
          npm pkg set devDependencies["playwright"]="1.55.0"
          npm pkg set devDependencies["vitest"]="2.1.9"
          npm pkg set devDependencies["@vitest/coverage-v8"]="2.1.9"
          npm pkg set devDependencies["jsdom"]="24.1.3"
          npm pkg set devDependencies["@testing-library/react"]="15.0.7"
          npm pkg set devDependencies["@testing-library/jest-dom"]="6.8.0"

      - name: Regenerate lockfile only
        run: npm install --package-lock-only

      - name: Commit lockfile
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package.json package-lock.json
            git commit -m "chore: repair package-lock.json to match test deps"
            git push
          fi
