name: Repair Lockfile

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  repair:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Regenerate lockfile to exactly match package.json with npm@10 (Node 20)
      - name: Regenerate package-lock.json
        run: npm install --package-lock-only

      - name: Commit lockfile changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: repair package-lock.json to match package.json"
            git push
          fi
