name: tests

on: [push, pull_request]

jobs:
  unit-and-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          registry-url: https://registry.npmjs.org

      - name: Verify lockfile (fail fast)
        run: npm ci --no-audit --no-fund --dry-run

      - name: Install deps
        run: npm ci --no-audit --no-fund

      # ---- UNIT (Vitest) ----
      - name: Run unit tests (Vitest)
        run: npx vitest run --reporter=dot --coverage

      # ---- BUILD for Playwright preview ----
      - name: Build app
        run: npm run build

      # ---- E2E (Playwright) ----
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E (Playwright)
        run: npx playwright test e2e --reporter=html

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
