name: tests

on:
  # manual trigger
  workflow_dispatch:
    inputs:
      run_e2e:
        description: "Also run Playwright e2e?"
        type: boolean
        default: true
  # once a day (cron is in UTC)
  schedule:
    - cron: "30 03 * * *"   # 09:00 IST (Asia/Kolkata is UTC+5:30)

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-and-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: https://registry.npmjs.org

      - run: npm ci --no-audit --no-fund
      - run: npx vitest run src --reporter=dot --coverage

      - if: ${{ inputs.run_e2e || github.event_name == 'schedule' }}
        run: npm run build
      - if: ${{ inputs.run_e2e || github.event_name == 'schedule' }}
        run: npx playwright install --with-deps chromium
      - if: ${{ inputs.run_e2e || github.event_name == 'schedule' }}
        run: npx playwright test --project=chromium e2e --reporter=html
