# .github/workflows/tests.yml
name: tests

on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci --no-audit --no-fund
      - run: npm run test:unit -- --run

  e2e-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci --no-audit --no-fund
      - run: npx playwright install --with-deps
      - run: npm run build
      - run: npx http-server dist -p 4173 & sleep 2
      - run: npx playwright test --project=chromium e2e --reporter=html
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

  # Optional, manual integration against DEV Supabase
  e2e-integration:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.DEV_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.DEV_SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci --no-audit --no-fund
      - run: npx playwright install --with-deps
      - run: npm run build
      - run: npx http-server dist -p 4173 & sleep 2
      - run: npx playwright test --project=chromium e2e-integration --reporter=html
