name: tests

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  unit:
    name: Unit tests (Vitest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (lockfile)
        run: npm ci --no-audit --no-fund

      - name: Run unit tests
        run: npx vitest --run --reporter=dot

  e2e:
    name: E2E tests (Playwright)
    needs: unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (lockfile)
        run: npm ci --no-audit --no-fund

      - name: Install Playwright (Chromium + deps)
        run: npx playwright install --with-deps chromium
        # ffmpeg is optional; add if your tests need it:
        # run: npx playwright install ffmpeg

      # If your e2e tests require a built app, uncomment the two steps below:
      # - name: Build
      #   run: npm run build
      # - name: Preview server (background)
      #   run: npx serve -s dist -l 4173 &

      - name: Run e2e tests (Chromium)
        run: npx playwright test --project=chromium e2e --reporter=html

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
